# Generated by Django 3.2 on 2023-04-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_created_genrefilmwork_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='created',
            new_name='created_at',
        ),
    ]
